# Generated by Django 5.1 on 2024-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_droplocation_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droplocation',
            name='drop_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='drop_x_coordinate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='drop_y_coordinate',
            field=models.IntegerField(default=1),
        ),
    ]
