# Generated by Django 5.1 on 2024-08-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_droplocation_drop_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('base_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_x_coordinate', models.FloatField()),
                ('base_y_coordinate', models.FloatField()),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('pickup_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_x_coordinate', models.FloatField()),
                ('pickup_y_coordinate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='drop_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='drop_x_coordinate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='drop_y_coordinate',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('drone_id', models.AutoField(primary_key=True, serialize=False)),
                ('battery_percentage', models.IntegerField()),
                ('is_fault', models.BooleanField()),
                ('velocity', models.IntegerField()),
                ('drone_x_coordinate', models.FloatField()),
                ('drone_y_coordinate', models.FloatField()),
                ('drone_z_coordinate', models.FloatField()),
                ('is_package_load', models.BooleanField()),
                ('is_package_unload', models.BooleanField()),
                ('last_communication', models.IntegerField()),
                ('step_index', models.IntegerField()),
                ('ready_for_delivery', models.BooleanField()),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.base')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_collected', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('delivery_date', models.IntegerField()),
                ('drop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.droplocation')),
                ('drone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drone')),
                ('pickup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pickuplocation')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_index', models.AutoField(primary_key=True, serialize=False)),
                ('drone_x_coordinate', models.FloatField()),
                ('drone_y_coordinate', models.FloatField()),
                ('drone_z_coordinate', models.FloatField()),
                ('drone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drone')),
            ],
        ),
    ]
