# Generated by Django 5.1 on 2024-08-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_base_pickuplocation_alter_droplocation_drop_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='drone_id',
            new_name='drone',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='drop_id',
            new_name='drop',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='pickup_id',
            new_name='pickup',
        ),
        migrations.RenameField(
            model_name='drone',
            old_name='base_id',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='drone_id',
            new_name='drone',
        ),
    ]
