# Generated by Django 5.1 on 2024-09-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_drone_id_delivery_drone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='base',
        ),
        migrations.RemoveField(
            model_name='step',
            name='drone',
        ),
        migrations.RenameModel(
            old_name='DropLocation',
            new_name='DropLocations',
        ),
        migrations.RenameModel(
            old_name='PickupLocation',
            new_name='PickupLocations',
        ),
        migrations.RenameModel(
            old_name='Base',
            new_name='Bases',
        ),
        migrations.CreateModel(
            name='Drones',
            fields=[
                ('drone_id', models.AutoField(primary_key=True, serialize=False)),
                ('battery_percentage', models.IntegerField()),
                ('is_fault', models.BooleanField()),
                ('velocity', models.IntegerField()),
                ('drone_x_coordinate', models.FloatField()),
                ('drone_y_coordinate', models.FloatField()),
                ('drone_z_coordinate', models.FloatField()),
                ('is_package_load', models.BooleanField()),
                ('is_package_unload', models.BooleanField()),
                ('last_communication', models.IntegerField()),
                ('planned_start_time', models.IntegerField()),
                ('step_index', models.IntegerField()),
                ('ready_for_delivery', models.BooleanField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bases')),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_collected', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('requested_date', models.IntegerField()),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.droplocations')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pickuplocations')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drones')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_index', models.IntegerField()),
                ('drone_x_coordinate', models.FloatField()),
                ('drone_y_coordinate', models.FloatField()),
                ('drone_z_coordinate', models.FloatField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drones')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Drone',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
