# Generated by Django 5.1 on 2024-09-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_obstacles_alter_bases_base_x_coordinate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bases',
            table='bases',
        ),
        migrations.AlterModelTable(
            name='deliveries',
            table='deliveries',
        ),
        migrations.AlterModelTable(
            name='drones',
            table='drones',
        ),
        migrations.AlterModelTable(
            name='droplocations',
            table='drop_locations',
        ),
        migrations.AlterModelTable(
            name='obstacles',
            table='obstacles',
        ),
        migrations.AlterModelTable(
            name='pickuplocations',
            table='pickup_locations',
        ),
        migrations.AlterModelTable(
            name='steps',
            table='steps',
        ),
    ]
