# Generated by Django 5.1 on 2024-09-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_bases_table_alter_deliveries_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_message', models.TextField(null=True)),
                ('log_level', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drone_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drones')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
